import { readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { loadEnv } from 'vite'
import { load } from 'cheerio'
import { render, canonicalPaths, metadataFor } from '../.cache/site-ssr/prerender.js'

const env = loadEnv('production', process.cwd(), 'VITE_')
const origin = new URL(env.VITE_SITE_URL || 'https://santosrock.com').origin
const template = await readFile('dist/index.html', 'utf8')
const legacy = JSON.parse(await readFile('src/data/legacy-routes.json', 'utf8'))
const posts = JSON.parse(await readFile('src/data/blog-posts.json', 'utf8'))
const pages = JSON.parse(await readFile('src/data/site-pages.json', 'utf8'))
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')

async function output(file, text) {
  await mkdir(path.dirname(file), { recursive: true })
  await writeFile(file, text)
}
function documentFor(route) {
  const $ = load(template)
  const metadata = metadataFor(route)
  $('title').text(metadata.title)
  $('meta[name="description"]').attr('content', metadata.description)
  $('#root').html(render(route))
  if (metadata.noindex) $('head').append('<meta data-site-meta name="robots" content="noindex">')
  else {
    $('head').append(`<link data-site-meta rel="canonical" href="${escape(origin + route)}">`)
    for (const [key, value] of Object.entries({ 'og:title': metadata.title, 'og:description': metadata.description, 'og:url': origin + route, 'og:type': metadata.type, ...(metadata.image ? { 'og:image': origin + metadata.image } : {}) })) $('head').append(`<meta data-site-meta property="${key}" content="${escape(value)}">`)
  }
  return $.html()
}

for (const route of canonicalPaths) await output(path.join('dist', route, 'index.html'), documentFor(route))
await output('dist/404.html', documentFor('/404/'))
await output('dist/en-construccion/index.html', documentFor('/en-construccion/'))

const feedPaths = new Set([...legacy.inventory.filter(route => route.kind === 'feed').map(route => route.path), ...posts.map(post => `${new URL(post.sourceUrl).pathname}feed/`)])
for (const route of feedPaths) {
  const tag = legacy.tags.find(tag => route === `/tag/${tag.slug}/feed/`)
  const entries = route === '/feed/' ? posts : tag ? posts.filter(post => tag.postIds.includes(post.id)) : []
  const title = tag ? `${tag.name} | Santos Rock` : route === '/feed/' ? 'Santos Rock' : 'Comentarios | Santos Rock'
  const rss = `<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>${escape(title)}</title><link>${escape(origin + (tag ? `/tag/${tag.slug}/` : '/'))}</link><description>Santos Rock – Festival de música en la Zona de los Santos</description><language>es-CR</language><atom:link href="${escape(origin + route)}" rel="self" type="application/rss+xml"/>${entries.map(post => `<item><title>${escape(post.title)}</title><link>${escape(origin + new URL(post.sourceUrl).pathname)}</link><guid isPermaLink="true">${escape(origin + new URL(post.sourceUrl).pathname)}</guid><description>${escape(post.excerpt)}</description></item>`).join('')}</channel></rss>`
  await output(path.join('dist', route, 'index.xml'), rss)
}
await output('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${canonicalPaths.map(route => {
  const modified = pages.find(page => page.path === route)?.modified?.slice(0, 10)
  return `<url><loc>${escape(origin + route)}</loc>${modified ? `<lastmod>${modified}</lastmod>` : ''}</url>`
}).join('')}</urlset>\n`)
await output('dist/robots.txt', `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`)

// Hosting rules preserve original 200 URLs. Only the React prototype aliases move.
const redirects = [...legacy.redirects, ...canonicalPaths.filter(route => route !== '/').map(route => ({ from: route.slice(0, -1), to: route }))]
const mediaMappings = new Map()
for (const file of ['docs/blog-migration-report.json', 'docs/page-migration-report.json']) {
  const report = JSON.parse(await readFile(file, 'utf8'))
  for (const asset of report.assets) if (!mediaMappings.has(new URL(asset.source).pathname)) mediaMappings.set(new URL(asset.source).pathname, asset.local)
}
redirects.push(...[...mediaMappings].map(([from, to]) => ({ from, to })))
const regexEscape = value => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const apache = ['# Generated by Santos Rock. Deploy with the complete dist directory.', 'DirectoryIndex index.html', 'ErrorDocument 404 /404.html', '<IfModule mod_rewrite.c>', 'RewriteEngine On', ...redirects.map(rule => `RewriteRule ^${regexEscape(decodeURIComponent(rule.from.slice(1)))}$ ${rule.to} [R=301,L,NE]`), ...[...feedPaths].map(route => `RewriteRule ^${regexEscape(route.slice(1))}?$ ${route}index.xml [L]`), 'RewriteCond %{REQUEST_FILENAME} -f [OR]', 'RewriteCond %{REQUEST_FILENAME} -d', 'RewriteRule ^ - [L]', 'RewriteRule ^ - [R=404,L]', '</IfModule>', '']
await output('dist/.htaccess', apache.join('\n'))
// Both static hosts use the root 404.html automatically. Cloudflare does not
// accept 404 rewrites in _redirects, so keep the shared file to 301/200 rules.
await output('dist/_redirects', [...redirects.map(rule => `${rule.from} ${rule.to} 301`), ...[...feedPaths].map(route => `${route} ${route}index.xml 200`), ''].join('\n'))
await output('docs/route-migration-report.json', JSON.stringify({ originalSitemapRoutes: legacy.inventory, canonicalHtmlRoutes: canonicalPaths, feeds: [...feedPaths], redirects, notes: ['HTML includes complete React-rendered page content before JavaScript.', 'Comment feeds are retained as valid empty RSS channels; old comments were outside the migration scope.', 'Apache and Netlify/Cloudflare-compatible rules are generated in dist. Hosting support must be confirmed at publication.'] }, null, 2) + '\n')
console.log(`Prerendered ${canonicalPaths.length} canonical pages; preserved ${legacy.inventory.length} sitemap routes; generated ${feedPaths.size} RSS feeds and HTTP redirect rules.`)
